### ISSUE TITLE
Implement the Doubly Linked List 

### ISSUE THREAD

**Issue by ShaileshKumar007** [GDSC-CEC/HacktoberFest-2022-Python#51]
## Implement the Doubly Linked List 
Put your solution inside the solution.py file.
This problem is inside medium foler.

**Comment by hamzabohra** [comment]
please can i work on this?

**Comment by Anamaya1729** [comment]
Sure @hamzabohra assigned you.

**Comment by ShaileshKumar007** [comment]
> Hi @ShaileshKumar007, please assign this issue to me

@Ash0069 
hamzabohra is currently working on this issue. You can create new issues for the problems you would like to work on. I'll assign that issue to you

**Comment by Ash0069** [comment]
@ShaileshKumar007 so can i work on infix to postfix conversion issue if possible

**Comment by Anamaya1729** [comment]
Completed in #54
