### ISSUE TITLE
Implement the Binary Search

### ISSUE THREAD

**Issue by ShaileshKumar007** [GDSC-CEC/HacktoberFest-2022-Python#52]
## Implement the Binary Search
Write your code inside the solution.py file
The problem is inside easy folder

**Comment by thechangamunda** [comment]
Assign the issue to me, I would like to contribute.

**Comment by hamzabohra** [comment]
hi can i work on this issue?

**Comment by musaddiq-ashfaq** [comment]
I want to contribute, assign it to me

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by Ash0069** [comment]
Hi @ShaileshKumar007, please assign this to me

**Comment by ShaileshKumar007** [comment]
> Assign the issue to me, I would like to contribute.

@thechangamunda great. I'm assigning this issue to you

**Comment by ShaileshKumar007** [comment]
You all can create issues for the problems on which you want to work on. I'll assign you your respective issues.

**Comment by rxhith** [comment]
I would like to work on this ,can u assign me

**Comment by combatantash** [comment]
Can you please assign me this issue

**Comment by srishtig2412** [comment]
Hi can you please assign this issue to me?
