### ISSUE TITLE
error in   tests.py in fibonacci_iterative folder

### ISSUE THREAD

**Issue by ayush4345** [GDSC-CEC/HacktoberFest-2022-Python#57]
![image](https://user-images.githubusercontent.com/99096397/196891384-1d373081-f8ac-4c65-bfaa-2ac440552243.png)
there should be an argument in the solution function, but it is missing.
all the test case is passed in my code except this one.
should I pass my argument on my own in solution function of tests.py or  u will change??

**Comment by Anamaya1729** [comment]
It's not an error, it was intended this way. It was written to stop just copy pasting of code and check if your function is robust enough to handle edge cases and exceptions. Please don't change the test cases, find the way to pass them as there are many.
